"""Seed the Model Arena demo workspace + per-lane git worktrees, from scratch.

Creates a small standalone git repo, `arena-target`, as a sibling directory
to this S17Code checkout, with two deliberately seeded bugs (mathkit/stats.py,
mathkit/dedupe.py) and their tests. Then creates one git worktree per lane
(`arena-worktrees/{groq,gemini,nvidia}`, also siblings), each on its own
branch off `arena-target`'s `main`, so three agents can edit independently
without racing on the same files.

Safe to run once on a fresh clone. Refuses if the target already exists,
rather than overwriting a demo setup in progress -- use
`arena/reset_workspaces.py` to restore worktrees to this seeded state
between takes instead of re-running this script.

Run from the S17Code repo root: ``uv run python arena/seed_target.py``
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ARENA_TARGET = REPO_ROOT.parent / "arena-target"
WORKTREES_DIR = REPO_ROOT.parent / "arena-worktrees"
LANES = ("groq", "gemini", "nvidia")

STATS_PY = '''"""Small stats helpers for the demo workspace."""


def average(values):
    """Return the arithmetic mean of ``values``."""
    return sum(values) / len(values)
'''

DEDUPE_PY = '''"""Small collection helpers for the demo workspace."""


def dedupe_preserve_order(items):
    """Return ``items`` with duplicates removed, keeping first-seen order."""
    return list(set(items))
'''

TEST_STATS_PY = '''import pytest

from mathkit.stats import average


def test_average_of_values():
    assert average([2, 4, 6]) == 4


def test_average_of_empty_list_raises_value_error():
    with pytest.raises(ValueError):
        average([])
'''

TEST_DEDUPE_PY = '''from mathkit.dedupe import dedupe_preserve_order


def test_dedupe_preserves_first_seen_order():
    assert dedupe_preserve_order([3, 1, 3, 2, 1, 4]) == [3, 1, 2, 4]


def test_dedupe_handles_no_duplicates():
    assert dedupe_preserve_order([1, 2, 3]) == [1, 2, 3]
'''

PYPROJECT_TOML = '''[project]
name = "mathkit"
version = "0.1.0"
description = "Seeded demo workspace for Model Arena -- do not fix these bugs by hand."
requires-python = ">=3.10"

[tool.pytest.ini_options]
testpaths = ["tests"]
'''

GITIGNORE = '''__pycache__/
*.pyc
.pytest_cache/
'''

TARGET_README = '''# mathkit (Model Arena demo workspace)

A small, deliberately seeded demo repository. It exists purely so Model Arena's coding
lanes have something real to fix on camera.

- `mathkit/stats.py` -- `average([])` raises `ZeroDivisionError` instead of a clear
  `ValueError`. `tests/test_stats.py` is red on a clean checkout.
- `mathkit/dedupe.py` -- `dedupe_preserve_order` drops both duplicates *and* the original
  order (`list(set(items))`). `tests/test_dedupe.py` is red on a clean checkout.

Each lane in Model Arena works from its own `git worktree` of this repo's `main` branch.
Run `python arena/reset_workspaces.py` (in the `S17Code` repo) between takes to restore
every worktree to this seeded state. Generated by `arena/seed_target.py`.
'''


def _run(argv: list[str], cwd: Path) -> None:
    subprocess.run(argv, cwd=cwd, check=True, capture_output=True, text=True)


def main() -> int:
    if ARENA_TARGET.exists():
        print(f"refusing to seed: {ARENA_TARGET} already exists.")
        print("If this is a fresh clone gone wrong, remove it by hand first.")
        print("If a demo is already in progress, use arena/reset_workspaces.py instead.")
        return 1

    (ARENA_TARGET / "mathkit").mkdir(parents=True)
    (ARENA_TARGET / "tests").mkdir(parents=True)
    (ARENA_TARGET / "mathkit" / "__init__.py").write_text("", encoding="utf-8")
    (ARENA_TARGET / "mathkit" / "stats.py").write_text(STATS_PY, encoding="utf-8")
    (ARENA_TARGET / "mathkit" / "dedupe.py").write_text(DEDUPE_PY, encoding="utf-8")
    (ARENA_TARGET / "tests" / "__init__.py").write_text("", encoding="utf-8")
    (ARENA_TARGET / "tests" / "test_stats.py").write_text(TEST_STATS_PY, encoding="utf-8")
    (ARENA_TARGET / "tests" / "test_dedupe.py").write_text(TEST_DEDUPE_PY, encoding="utf-8")
    (ARENA_TARGET / "pyproject.toml").write_text(PYPROJECT_TOML, encoding="utf-8")
    (ARENA_TARGET / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
    (ARENA_TARGET / "README.md").write_text(TARGET_README, encoding="utf-8")

    _run(["git", "init", "-b", "main"], cwd=ARENA_TARGET)
    _run(["git", "add", "-A"], cwd=ARENA_TARGET)
    _run(["git", "-c", "user.email=arena@local", "-c", "user.name=Model Arena",
          "commit", "-m",
          "Seed mathkit: average() empty-list ZeroDivisionError, "
          "dedupe_preserve_order drops order"],
         cwd=ARENA_TARGET)
    print(f"seeded {ARENA_TARGET}")

    WORKTREES_DIR.mkdir(exist_ok=True)
    for lane in LANES:
        lane_dir = WORKTREES_DIR / lane
        if lane_dir.exists():
            print(f"skipping worktree for {lane}: {lane_dir} already exists.")
            continue
        _run(["git", "worktree", "add", "-b", f"lane/{lane}", str(lane_dir), "main"],
             cwd=ARENA_TARGET)
        print(f"worktree ready: {lane_dir}")

    print("\nDone. Next: copy arena/env/*.env.example to *.env and fill in your paths/token.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
